### ISSUE TITLE
Remote symbol disappeared

### ISSUE THREAD

**Issue by boris779** [GPlay97/EVNotify#67]
### New issue
- Short description: Remote Symbol disappeared
- Detailed description: After Upgrade to 1.2.0:08 the New Feature was activated. But now it is not displayed anymore

- Can you reproduce it? (_If so, how?_):

- [ ] critical issue? (_issue, which will affect multiple accounts, 
  an issue which prevents that you can use the app in a normal way,
  bug which makes app unusable, security breach*_) (Yes/No): NO
  
 <details>
  <summary>additional information</summary>
  

  (_such as AKey [**NEVER EVER SHARE YOUR TOKEN!**], images_ or debug data from overview -> debug icon, your phone and android version)
Android 8
Screenshot available

</details>

\* **For very critical security breaches, please mail directly at info@evnotify.de**

**Comment by GPlay97** [comment]
The remote control feature was just an April fool's joke. It was only "available" yesterday. Since it didn't really work and was just a joke, it automatically hides now. The "fake" code for it will removed within the next update. The next update then will get real features again ;-)
