### ISSUE TITLE
Question : Hyundai Kona support - Esim OBD device support

### ISSUE THREAD

**Issue by asetyde** [GPlay97/EVNotify#90]
Hi,
I'm embedded engineer with Hyundai Kona EV, I see your project but I want do a similar but more simple system to monitor charge of vehicle.
I want use this scheme : 
OBD2 -> EMBEDDED SIM DEVICE -> SERVER/APP
OBD2-SIM DEVICE -> SMS/SERVER SERVICE
OBD2 with interface to embedded device esim -> to app server or direct to sms or similar (integrate with EVNotify ? )

But at first I need to understand how read from obd and what , can you help me ? I have iOS but also android in my lab

**Comment by asetyde** [comment]
we can start from here and i find a support esim device
http://arduinodev.com/hardware/obd-kit/

**Comment by asetyde** [comment]
https://freematics.com/store/index.php?route=product/product&path=20&product_id=82

**Comment by asetyde** [comment]
As you can see I must use AT command of this interface to test preliminary functions of OBD, but at first I must understand if I try to access to battery status .. and how ...

**Comment by GPlay97** [comment]
Currently it's completely unknown how to be able to interact with the Kona EV. All comands for the IONIQ won't work for the Kona. Unfortunately.
It must be reversed engineered, before the command can be sent.

**Comment by asetyde** [comment]
Oh !! Mmm about ioniq where do you find or how you find OBD commands

**Comment by GPlay97** [comment]
Basically, what has been reversed engineered by others. Here is a good overview: https://github.com/JejuSoul/OBD-PIDs-for-HKMC-EVs/blob/master/Ioniq%20EV/extendedpids/Hyundai_Ioniq_EV_BMS_data.csv

**Comment by asetyde** [comment]
https://github.com/JejuSoul/OBD-PIDs-for-HKMC-EVs/issues/22
